# Sample file for AWS CodeBuild
version: 0.2

phases:
  install:
    commands:
       - echo "Downloading Terraform for JSON conversion"
       - wget https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_linux_amd64.zip
       - unzip terraform*.zip
       - mv terraform /usr/local/bin
       - terraform --version
       - terraform init
       - terraform plan --out tfplan.binary
       - terraform show -json tfplan.binary > tfplan.json
       - echo "JSON Output using Terraform show"
       - cat tfplan.json
       - echo "Downloading OPA eval file"
       - curl -L -o opa https://openpolicyagent.org/downloads/v0.40.0/opa_linux_amd64_static
       - chmod 755 ./opa
       - echo "OPA Policy Validation Command, replace the -d value to the rego file name you want to evaluate against."
       - ./opa eval --format pretty -i tfplan.json -d <FILE_NAME>.rego "data"
       - ./opa eval --format pretty -i tfplan.json -d <FILE_NAME>.rego "data" | jq --raw-output '.opa_policies.allow' > allow.txt
       - ALLOW_VALUE=`cat allow.txt`
       - echo "Allow Value Below:"
       - echo $ALLOW_VALUE
       - if [ $ALLOW_VALUE = 'false' ]; then exit 1; fi